#!/bin/bash
# For usage with Travis CI
numJson=$(ls -1 build/signs/ | grep .json$ | wc -l)
numCson=$(ls -1 dev/ | grep .cson$ | wc -l)

if [ $numJson -ne $numCson ]
then
  echo "Not all *.json files were generated."
  exit 1
fi

if [ ! -f build/gh-pages/examples.html ] || [ ! -f build/gh-pages/examples.scss ]
then
  echo "The example page for gh-pages has not been generated."
  exit 1
fi

exit 0
